name: 5748music
favicon: null
layout_spectrum: 0.06415170733816922
typography_spectrum: 0.2844190567266196
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e4563b'
    - '#008e84'
    - '#f2a55a'
    - '#4c2644'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.9123341231606901
  rhythmicContrast: 0.75
purpose: []
